"""Add payment_mode to Distribution

Revision ID: e01615971741
Revises: 
Create Date: 2025-03-15 13:18:21.122744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01615971741'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_mode', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('distribution', schema=None) as batch_op:
        batch_op.drop_column('payment_mode')

    # ### end Alembic commands ###
